# Generated by Django 5.1.11 on 2025-08-23 11:19

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "db",
            "0014_remove_run_is_managed_project_archived_at_and_duration_wait_time_to_float_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projectstats",
            name="resources",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectstats",
            name="wait_time",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
