# Generated by Django 5.2.14 on 2026-05-20 17:36

import django.core.validators
import django.db.models.deletion
import haupt.common.validation.blacklist
import re
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_project_user_projectversion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSshKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), haupt.common.validation.blacklist.validate_blacklist_name])),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key_type', models.CharField(max_length=32)),
                ('public_key', models.TextField()),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'db_usersshkey',
                'abstract': False,
            },
        ),
    ]
