line-length = 88

[lint]
select = ["E4", "E7", "E9", "F", "I"]

[lint.isort]
known-first-party = ["polyaxon", "traceml", "hypertune", "haupt", "licenser", "ee", "vents", "clipped", "tests"]
known-third-party = ["celery", "corsheaders", "datadog", "docker", "orjson", "picklefield", "pydantic", "rest_framework", "scipy", "sentry_sdk", "sklearn"]
extra-standard-library = ["typing", "typing_extensions", "mock", "pytest", "factory", "faker", "flaky", "numpy", "pandas", "requests", "websocket", "jinja2", "yaml", "pytz"]
force-single-line = false
force-sort-within-sections = true
combine-as-imports = true
lines-after-imports = 2
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "I"]
