#!/bin/bash

if [ $? -eq 0 ]; then
    if [ "$1" = "local-sqlite" ]; then
        cmd/python sqlite haupt/manage.py ${@:2}
    elif [ "$1" = "container-sqlite" ]; then
        cmd/python docker-sqlite haupt/manage.py ${@:2}
    elif [ "$1" = "container-pgsql" ]; then
        cmd/python pgsql haupt/manage.py ${@:2}
    fi
fi
