#!/bin/bash
if [ $? -eq 0 ]; then
    echo "========================"
    echo "build base dev"
    echo "========================"
    docker build -f .docker/DockerfileDevArm -t haupt:dev .
    echo "========================"
fi
