#!/bin/bash
if [ $? -eq 0 ]; then
    echo "========================"
    echo "pull base"
    echo "========================"
    docker pull polyaxon/polyaxon-base
    echo "========================"
    echo "build base dev"
    echo "========================"
    docker build -f docker/DockerfileDev -t haupt:dev .
    echo "========================"
fi
